version: "3.8"
services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: task_management
    volumes:
      - db-data:/var/lib/mysql

  backend:
    build: ./backend
    ports:
      - "4000:4000"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASS: example
      DB_NAME: task_management
      DB_DIALECT: mysql
      JWT_SECRET: your_secret_key
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    environment:
      VITE_API_BASE_URL: "http://backend:4000/api"
    depends_on:
      - backend

volumes:
  db-data:
